AUTO_RESUME: true
CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
DATA_DIR: ''

OUTPUT_DIR: 'experiments/output'
LOG_DIR: 'experiments/log'
WORKERS: 4
PRINT_FREQ: 100

DATASET:
  DATASET: 'MyKeypointDataset'
  ROOT: 'data'
  TRAIN_SET: 'train'
  TEST_SET: 'val'
  DATA_FORMAT: jpeg
  FLIP: false
  SCALE_FACTOR: 0.0
  ROT_FACTOR: 0.0
  COLOR_RGB: true
  MEDICAL_AUGMENTATION: true
  MIXUP_CUTMIX: true

MODEL:
  INIT_WEIGHTS: true
  NAME: llrformer
  NUM_JOINTS: 36
  PRETRAINED: 'pretrained/imagenet/hrnet_w32-36af842e.pth'
  TARGET_TYPE: gaussian
  
  USE_CROSS_SELF_ATTENTION: true
  CROSS_SELF_ATTENTION_LAYERS: 6
  TRANSFORMER_DEPTH: 6
  TRANSFORMER_HEADS: 8
  TRANSFORMER_MLP_RATIO: 3
  POS_EMBEDDING_TYPE: 'sine-full'
  INIT: true
  DIM: 192
  PATCH_SIZE: [9, 3]
  IMAGE_SIZE: [384, 1152]
  HEATMAP_SIZE: [96, 288]
  SIGMA: 2
  DROPOUT_RATE: 0.1
  ATTENTION_DROPOUT: 0.1
  
  EXTRA:
    PRETRAINED_LAYERS:
    - 'conv1'
    - 'bn1'
    - 'conv2'
    - 'bn2'
    - 'layer1'
    - 'transition1'
    - 'stage2'
    - 'transition2'
    - 'stage3'
    FINAL_CONV_KERNEL: 1
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      FUSE_METHOD: SUM

TRAIN:
  BATCH_SIZE_PER_GPU: 1
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 250
  OPTIMIZER: adamw
  LR: 0.001
  LR_FACTOR: 0.7
  LR_STEP:
    - 120
    - 180
  WD: 0.0001
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false
  DROPOUT: 0.15
  PATIENCE: 12
  MIN_LR: 1e-6
  LR_SCHEDULER: 'ReduceLROnPlateau'
  JOINT_WEIGHTS: true
  FEMUR_TIBIA_WEIGHT: 2.0

TEST:
  BATCH_SIZE_PER_GPU: 1
  MODEL_FILE: 'experiments/output/MyKeypointDataset/llrformer/llrformer/model_best.pth'
  FLIP_TEST: false
  POST_PROCESS: true
  BLUR_KERNEL: 11

DEBUG:
  DEBUG: true
  SAVE_BATCH_IMAGES_GT: true
  SAVE_BATCH_IMAGES_PRED: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true

